name: "Main CI"

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.6"]

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: deblur
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        shell: bash -l {0}
        run: |
          conda create --yes -n deblur python=${{ matrix.python-version }} pip nose flake8 h5py
          conda activate deblur
          conda install --yes -c bioconda "VSEARCH=2.7.0" MAFFT=7.310 SortMeRNA=2.0
          pip install coveralls
          pip install -e .

      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate deblur
          nosetests --with-doctest --with-coverage --cover-package=deblur

  coveralls_finish:
    needs: main
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: flake8
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: python -m pip install --upgrade pip
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: lint
      run: |
       pip install -q flake8
       flake8 deblur scripts/deblur setup.py
